USE master

IF DB_ID('NEO_SALES') IS NOT NULL
BEGIN
    ALTER DATABASE NEO_SALES
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE NEO_SALES;
END;

CREATE DATABASE NEO_SALES;
GO

USE NEO_SALES;
GO


/* 
=========================================================
   TABLES
========================================================= 
*/

CREATE TABLE CUSTOMER
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [NAME] VARCHAR(256) NOT NULL,
    [NIT] VARCHAR(256) NULL,
    EMAIL VARCHAR(256) NOT NULL,
    [STATUS] BIT DEFAULT 1,
    DATETIME_CREATE DATETIME NOT NULL DEFAULT GETDATE(),
    DATETIME_UPDATE DATETIME NULL,
    USER_CREATE VARCHAR(128) NOT NULL,
    USER_UPDATE VARCHAR(128) NULL,
    
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);
GO

CREATE TABLE [PRODUCT]
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [NAME] VARCHAR(256) NOT NULL,
    PRICE DECIMAL(18, 2) NOT NULL,
    STOCK INT NOT NULL,
    [STATUS] BIT DEFAULT 1,
    DATETIME_CREATE DATETIME NOT NULL DEFAULT GETDATE(),
    DATETIME_UPDATE DATETIME NULL,
    USER_CREATE VARCHAR(128) NOT NULL,
    USER_UPDATE VARCHAR(128) NULL,
    
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);
GO

CREATE TABLE SALE_STATUS
(
    ID INT NOT NULL,
    [NAME] VARCHAR(32) NOT NULL,
    [DESCRIPTION] VARCHAR(256) NOT NULL,
    
    CONSTRAINT UQ_SALE_STATUS_NAME UNIQUE (NAME),
    CONSTRAINT PK_SALE_STATUS PRIMARY KEY (ID)
);
GO

CREATE TABLE SALE
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    ID_CUSTOMER UNIQUEIDENTIFIER NOT NULL,
    STATUS_ID INT NOT NULL,
    DATE DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_SALE_CUSTOMER
        FOREIGN KEY (ID_CUSTOMER)
        REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_SALE_STATUS
        FOREIGN KEY (STATUS_ID)
        REFERENCES SALE_STATUS(ID),
    CONSTRAINT PK_SALE PRIMARY KEY (ID)
);
GO


CREATE TABLE SALE_DETAIL
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    ID_SALE UNIQUEIDENTIFIER NOT NULL,
    ID_PRODUCT UNIQUEIDENTIFIER NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE_UNIT DECIMAL(18, 2) NOT NULL,

    CONSTRAINT PK_SALE_DETAIL
        PRIMARY KEY (ID),
    CONSTRAINT FK_SALE_DETAIL_SALE
        FOREIGN KEY (ID_SALE)
        REFERENCES SALE(ID),
    CONSTRAINT FK_SALE_DETAIL_PRODUCT
        FOREIGN KEY (ID_PRODUCT)
        REFERENCES [PRODUCT](ID)
);
GO