CREATE OR ALTER PROCEDURE sp_EXPIRE_SALES
(
    @p_MAX_MINUTES INT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @STATUS_PENDIENTE INT,
            @STATUS_EXPIRADA  INT;

    SELECT @STATUS_PENDIENTE = ID FROM SALE_STATUS WHERE [NAME] = 'PENDIENTE';
    SELECT @STATUS_EXPIRADA  = ID FROM SALE_STATUS WHERE [NAME] = 'EXPIRADA';

    IF @STATUS_PENDIENTE IS NULL OR @STATUS_EXPIRADA IS NULL
    BEGIN
        THROW 50002, 'Catalogo SALE_STATUS incompleto', 1;
    END;

    UPDATE SALE
    SET STATUS_ID = @STATUS_EXPIRADA
    OUTPUT
        INSERTED.ID,
        INSERTED.ID_CUSTOMER,
        INSERTED.STATUS_ID,
        INSERTED.[DATE]
    WHERE
        STATUS_ID = @STATUS_PENDIENTE
        AND DATEADD(MINUTE, @p_MAX_MINUTES, [DATE]) < GETDATE();
END;
GO
